server:
  shutdown: graceful
  port: 8906
  undertow:
    buffer-size: 1024
    direct-buffers: on
    always-set-keep-alive: true
spring:
  application:
    name: sparkzxl-sharding-demo
  lifecycle:
    timeout-per-shutdown-phase: 30s
  shardingsphere:
    datasource:
      # 所有数据源的名字
      names: ds-orders-0,ds-orders-1
      # 订单 orders 数据源配置 00
      ds-orders-0:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://sparkzxl.mysql.rds.aliyuncs.com/sparkzxl_order_0?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
        username: zhouxinlei
        password: Zxl298828
      # 订单 orders 数据源配置 01
      ds-orders-1:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://sparkzxl.mysql.rds.aliyuncs.com/sparkzxl_order_1?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
        username: zhouxinlei
        password: Zxl298828
    # 分片规则
    sharding:
      tables:
        # orders 表配置
        oms_order:
          actualDataNodes: ds-orders-0.oms_order_$->{[0,2,4,6]}, ds-orders-1.oms_order_$->{[1,3,5,7]}
          key-generator: # 主键生成策略
            column: id
            type: SNOWFLAKE
          database-strategy:
            inline:
              algorithm-expression: ds-orders-$->{member_id % 2}
              sharding-column: member_id
          table-strategy:
            inline:
              algorithm-expression: oms_order_$->{member_id % 8}
              sharding-column: member_id
    # 拓展属性配置
    props:
      sql:
        show: true # 打印 SQL
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.github.sparkzxl.sharding.infrastructure.entity
  custom:
    mapper-scan: com.github.sparkzxl.sharding.infrastructure.mapper
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.github.sparkzxl.sharding.infrastructure.mapper: debug
knife4j:
  enable: true
  description: sparkzxl 分库分表在线文档
  base-package: com.github.sparkzxl.sharding.interfaces
  group: 分库分表应用
  title: sparkzxl 分库分表在线文档
  terms-of-service-url: https://www.sparksys.top
  version: 1.0
  license: Powered By sparkzxl
  license-url: https://github.com/sparkzxl
  contact:
    name: zhouxinlei
    email: zhouxinlei298@163.com
    url: https://github.com/sparkzxl
