server:
  port: 8081
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.114.40.129:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
knife4j:
  enable: true
  description: sparkzxl nacos consumer在线文档
  base-package: com.github.sparkzxl.nacos.controller
  group: nacos consumer应用
  title: sparkzxl nacos consumer在线文档
  terms-of-service-url: https://www.sparksys.top
  version: 1.0
  license: Powered By sparkzxl
  license-url: https://github.com/sparkzxl
  contact:
    name: zhouxinlei
    email: zhouxinlei298@163.com
    url: https://github.com/sparkzxl
